{% set name = "reacton" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reacton-{{ version }}.tar.gz
  sha256: e1a65cc7df8732599137e1402b52bb54b0583c7a6af3e13c7c6d1e8e10409aec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - hatch
  run:
    - ipywidgets
    - python >=3.6
    - typing_extensions >=4.1.1

test:
  imports:
    - reacton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/reacton/
  summary: Write ipywidgets like React
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
