{% set name = "reacton" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reacton-{{ version }}.tar.gz
  sha256: a9de79cb4f71004f2735e9b058de26244aa676449e09203ab29a42628423e89a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - hatch
  run:
    - ipywidgets
    - python >=3.6
    - rich
    - typing_extensions

test:
  imports:
    - reacton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/reacton/
  summary: Write ipywidgets like React
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
